addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.2")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.9.19")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.13")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"       % "1.6.1")
addSbtPlugin("org.scala-sbt"             % "sbt-autoversion"     % "1.0.0")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.7.5")
