name: Deploy prod
on:
  push:
    branches:
      - 'master'
jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - uses: olafurpg/setup-scala@v6
        with:
          java-version: openjdk@1.14

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Run tests
        run: sbt clean coverage test coverageReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Increment version, tag, build an artifact and push it to GitHub package registry
        id: sbt-release
        outputs:
          tag:
            description: 'Latest tag'
        run: |
          git config user.email "alexander.melashchenko@gmail.com"
          git config user.name "GitHub Actions"
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u melalex --password-stdin
          sbt 'release skip-tests with-defaults'
          echo "::set-output name=latest-tag::$(git describe --abbrev=0)"

      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.sbt-release.outputs.tag }}
          release_name: Release ${{ steps.sbt-release.outputs.tag }}
          body_path: target/changelog/CHANGELOG.md
          draft: false
          prerelease: false

      - name: Install ansible
        run: |
          sudo apt update
          sudo apt install software-properties-common
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible

      - uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check terraform
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init terraform

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color terraform

      - name: Terraform Plan
        id: apply
        continue-on-error: true
        run: |
          terraform apply \
          -no-color \
          -auto-approve \
          -var '' \
          -var '' \
          terraform

      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          APPLY: "terraform\n${{ steps.apply.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖${{ steps.validate.outputs.stdout }}
            #### Terraform Apply 🚀\`${{ steps.apply.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`${process.env.APPLY}\`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

