name: Deploy prod
on: push
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v6
        with:
          java-version: openjdk@1.14

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Build, test and dockerize
        run: |
          echo "GITHUB_TOKEN" | docker login docker.pkg.github.com -u melalex --password-stdin
          sbt 'release with-defaults'