name: Check deployment scripts
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    paths:
      - 'ansible/*'
      - 'terraform/*'

jobs:
  validate-deployment:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
      TERRAFORM_WORKDIR: terraform
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check ${{ env.TERRAFORM_WORKDIR }}
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init ${{ env.TERRAFORM_WORKDIR }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color ${{ env.TERRAFORM_WORKDIR }}

      - name: Terraform Plan
        id: plan
        continue-on-error: true
        run: terraform plan -no-color ${{ env.TERRAFORM_WORKDIR }}

      - name: Lint Ansible Playbook
        id: ansible
        uses: ansible/ansible-lint-action@master
        with:
          targets: ansible/playbook.yml
        continue-on-error: true

      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖${{ steps.validate.outputs.stdout }}
            #### Terraform Plan 🚀\`${{ steps.plan.outcome }}\`
            #### Ansible Lint 🔨\`${{ steps.ansible.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`${{ steps.plan.outputs.stdout }}\`\`\`

            </details>

            <details><summary>Show Ansible lint</summary>

            \`\`\`${{ steps.ansible.outputs.stdout }}\`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Workflow: \`${{ github.workflow }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })